In [2]:
pip install pandas

Collecting pandas
  Using cached pandas-1.5.2-cp310-cp310-macosx_11_0_arm64.whl (10.8 MB)
Collecting numpy>=1.21.0
  Using cached numpy-1.24.1-cp310-cp310-macosx_11_0_arm64.whl (13.9 MB)
Collecting pytz>=2020.1
  Using cached pytz-2022.7-py2.py3-none-any.whl (499 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/homebrew/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-1.24.1 pandas-1.5.2 pytz-2022.7
Note: you may need to restart the kernel to use updated packages.

In [25]:
import pandas as pd
FILENAME = "Monthly_Top_10__2016-2022.csv"
df = pd.read_csv(FILENAME)

In [26]:
df

     year  month                     title           artist  rank
0    2022      1   첫 사랑니 (Rum Pum Pum Pum)             f(x)   1.0
1    2022      1                    ELEVEN        IVE (아이브)   2.0
2    2022      1           묻고싶다 (One Love)  Wanna One (워너원)   3.0
3    2022      1                       불장난        BLACKPINK   4.0
4    2022      1                       주인공               선미   5.0
..    ...    ...                       ...              ...   ...
733  2016     10               자장가를 활용한 신곡              장범준   8.0
734  2016     10            사랑에 빠졌죠 (당신만이)              장범준   9.0
735  2016     10  Red Queen (Feat. Zion.T)              아이유  10.0
736  2016     11                      None              NaN   NaN
737  2016     12                      None              NaN   NaN

[738 rows x 5 columns]

In [44]:
df['rank'] = df['rank'].fillna(-1).astype(int).replace({-1:None})
df

     year  month                     title           artist  rank
0    2022      1   첫 사랑니 (Rum Pum Pum Pum)             f(x)     1
1    2022      1                    ELEVEN        IVE (아이브)     2
2    2022      1           묻고싶다 (One Love)  Wanna One (워너원)     3
3    2022      1                       불장난        BLACKPINK     4
4    2022      1                       주인공               선미     5
..    ...    ...                       ...              ...   ...
733  2016     10               자장가를 활용한 신곡              장범준     8
734  2016     10            사랑에 빠졌죠 (당신만이)              장범준     9
735  2016     10  Red Queen (Feat. Zion.T)              아이유    10
736  2016     11                      None              NaN  None
737  2016     12                      None              NaN  None

[738 rows x 5 columns]

In [28]:
type(df)

pandas.core.frame.DataFrame

In [45]:
# rank의 값이 1인 것만 추출
is_top = df['rank'] == 1
first_song = df[is_top]
first_song[:30]

,year,month,title,artist,rank
0,2022,1,첫 사랑니 (Rum Pum Pum Pum),f(x),1
10,2022,2,그 사람,아이유,1
20,2022,3,그대를 잊는다는 건,다비치,1
30,2022,4,TOMBOY,(여자)아이들,1
40,2022,5,That That (prod. & feat. SUGA of BTS),싸이 (PSY),1
50,2022,6,넌 내게 반했어,노브레인 (NoBrain),1
61,2022,8,Attention,NewJeans,1
71,2022,9,Hype boy,NewJeans,1
81,2022,10,ANTIFRAGILE,LE SSERAFIM (르세라핌),1
91,2022,11,Ready For Love,BLACKPINK,1
99,2022,12,Ditto,NewJeans,1
109,2021,1,잠시,방탄소년단,1
119,2021,2,Celebrity,아이유,1
129,2021,3,Make It Right,방탄소년단,1
139,2021,4,라라라,SG 워너비,1
149,2021,5,Butter,방탄소년단,1
159,2021,6,Butter,방탄소년단,1
169,2021,7,Butter,방탄소년단,1
179,2021,8,Permission to Dance,방탄소년단,1
189,2021,9,Why So Lonely,원더걸스,1
199,2021,10,My Universe,"Coldplay, 방탄소년단",1
201,2021,11,묻고싶다 (One Love),Wanna One (워너원),1
205,2021,12,ELEVEN,IVE (아이브),1
210,2020,1,소우주 (Mikrokosmos),방탄소년단,1
220,2020,2,We are Bulletproof : the Eternal,방탄소년단,1
230,2020,3,00:00 (Zero O’Clock),방탄소년단,1
240,2020,4,시차,방탄소년단,1
250,2020,5,에잇(Prod.&Feat. SUGA of BTS),아이유,1
260,2020,6,에잇(Prod.&Feat. SUGA of BTS),아이유,1
270,2020,7,Old Town Road (Seoul Town Road Remix) feat. RM...,"Lil Nas X, RM",1

In [46]:
# year이 2022인 것만 추출
is_2022 = df['year'] == 2022
this_year = df[is_2022]
this_year

     year  month                    title           artist rank
0    2022      1  첫 사랑니 (Rum Pum Pum Pum)             f(x)    1
1    2022      1                   ELEVEN        IVE (아이브)    2
2    2022      1          묻고싶다 (One Love)  Wanna One (워너원)    3
3    2022      1                      불장난        BLACKPINK    4
4    2022      1                      주인공               선미    5
..    ...    ...                      ...              ...  ...
104  2022     12           Ready For Love        BLACKPINK    6
105  2022     12                 Dynamite            방탄소년단    7
106  2022     12                       봄날            방탄소년단    8
107  2022     12                   Cookie         NewJeans    9
108  2022     12                Attention         NewJeans   10

[109 rows x 5 columns]

In [47]:
# rank==1이면서 year==2022인 것만 추출
is_top = df['rank'] == 1
is_2022 = df['year'] == 2022
this_year_top_song = df[is_top & is_2022]
this_year_top_song

,year,month,title,artist,rank
0,2022,1,첫 사랑니 (Rum Pum Pum Pum),f(x),1
10,2022,2,그 사람,아이유,1
20,2022,3,그대를 잊는다는 건,다비치,1
30,2022,4,TOMBOY,(여자)아이들,1
40,2022,5,That That (prod. & feat. SUGA of BTS),싸이 (PSY),1
50,2022,6,넌 내게 반했어,노브레인 (NoBrain),1
61,2022,8,Attention,NewJeans,1
71,2022,9,Hype boy,NewJeans,1
81,2022,10,ANTIFRAGILE,LE SSERAFIM (르세라핌),1
91,2022,11,Ready For Love,BLACKPINK,1
99,2022,12,Ditto,NewJeans,1